In [1]:
import pandas as pd
from datetime import datetime

In [2]:
csv1 = pd.read_csv("202101-divvy-tripdata.csv")
csv2 = pd.read_csv("202102-divvy-tripdata.csv")
csv3 = pd.read_csv("202103-divvy-tripdata.csv")
csv4 = pd.read_csv("202104-divvy-tripdata.csv")
csv5 = pd.read_csv("202105-divvy-tripdata.csv")
csv6 = pd.read_csv("202106-divvy-tripdata.csv")
csv7 = pd.read_csv("202107-divvy-tripdata.csv")
csv8 = pd.read_csv("202108-divvy-tripdata.csv")
csv9 = pd.read_csv("202109-divvy-tripdata.csv")
csv10 = pd.read_csv("202110-divvy-tripdata.csv")
csv11 = pd.read_csv("202111-divvy-tripdata.csv")
csv12 = pd.read_csv("202112-divvy-tripdata.csv")
csv13 = pd.read_csv("202201-divvy-tripdata.csv")
csv14 = pd.read_csv("202202-divvy-tripdata.csv")
csv15 = pd.read_csv("202203-divvy-tripdata.csv")
csv16 = pd.read_csv("202204-divvy-tripdata.csv")
csv17 = pd.read_csv("202205-divvy-tripdata.csv")
csv18 = pd.read_csv("202206-divvy-tripdata.csv")
csv19 = pd.read_csv("202207-divvy-tripdata.csv")
csv20 = pd.read_csv("202208-divvy-tripdata.csv")
csv21 = pd.read_csv("202209-divvy-tripdata.csv")
csv22 = pd.read_csv("202210-divvy-tripdata.csv")
csv23 = pd.read_csv("202211-divvy-tripdata.csv")
csv24 = pd.read_csv("202212-divvy-tripdata.csv")

In [3]:
#df = pd.concat([csv1, csv2, csv3, csv4, csv5, csv6, csv7, csv8, csv9, csv10, csv11, csv12, csv13, csv14, csv15, csv16, csv17, csv18, csv19, csv20, csv21,csv22, csv23, csv24])
#df = pd.concat([csv1, csv2, csv3, csv4, csv5, csv6, csv7, csv8, csv9, csv10, csv11, csv12])
df = pd.concat([csv1, csv2, csv3, csv4, csv5, csv6])

In [4]:
df.isna().sum()

ride_id                    0
rideable_type              0
started_at                 0
ended_at                   0
start_station_name    187412
start_station_id      187412
end_station_name      205117
end_station_id        205117
start_lat                  0
start_lng                  0
end_lat                 1920
end_lng                 1920
member_casual              0
dtype: int64

In [5]:
df=df.dropna(subset=['end_station_name','end_station_id'])

In [6]:
df=df.dropna(subset=['start_station_name','start_station_id'])

In [7]:
df.isna().sum()

ride_id               0
rideable_type         0
started_at            0
ended_at              0
start_station_name    0
start_station_id      0
end_station_name      0
end_station_id        0
start_lat             0
start_lng             0
end_lat               0
end_lng               0
member_casual         0
dtype: int64

In [8]:
df['started_at_time'] = df['started_at'].apply(lambda x: datetime.strptime(x, '%Y-%m-%d %H:%M:%S'))

In [9]:
df['ended_at_time'] = df['ended_at'].apply(lambda x: datetime.strptime(x, '%Y-%m-%d %H:%M:%S'))

In [10]:
df['duration_time']=df['ended_at_time']-df['started_at_time']

In [11]:
negatives = df['duration_time'] < pd.Timedelta(0)
df = df.loc[~negatives]

In [12]:
df['duration_time'] = df['duration_time'].apply(lambda x: str(x)[-8:])

In [13]:
df.to_csv("divvy_2021-2022.csv",index=False)

In [14]:
df

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,started_at_time,ended_at_time,duration_time
9,B9F73448DFBE0D45,classic_bike,2021-01-24 19:15:38,2021-01-24 19:22:51,California Ave & Cortez St,17660,Wood St & Augusta Blvd,657,41.900363,-87.696704,41.899181,-87.672200,member,2021-01-24 19:15:38,2021-01-24 19:22:51,00:07:13
10,457C7F4B5D3DA135,electric_bike,2021-01-23 12:57:38,2021-01-23 13:02:10,California Ave & Cortez St,17660,California Ave & North Ave,13258,41.900406,-87.696733,41.910435,-87.696890,member,2021-01-23 12:57:38,2021-01-23 13:02:10,00:04:32
11,57C750326F9FDABE,electric_bike,2021-01-09 15:28:04,2021-01-09 15:37:51,California Ave & Cortez St,17660,Wood St & Augusta Blvd,657,41.900374,-87.696688,41.899180,-87.672178,casual,2021-01-09 15:28:04,2021-01-09 15:37:51,00:09:47
12,4D518C65E338D070,electric_bike,2021-01-09 15:28:57,2021-01-09 15:37:54,California Ave & Cortez St,17660,Wood St & Augusta Blvd,657,41.900379,-87.696716,41.899149,-87.672177,casual,2021-01-09 15:28:57,2021-01-09 15:37:54,00:08:57
13,9D08A3AFF410474D,classic_bike,2021-01-24 15:56:59,2021-01-24 16:07:08,California Ave & Cortez St,17660,Wood St & Augusta Blvd,657,41.900363,-87.696704,41.899181,-87.672200,casual,2021-01-24 15:56:59,2021-01-24 16:07:08,00:10:09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
729578,03087E3FF2C31427,classic_bike,2021-06-11 13:40:19,2021-06-11 13:54:39,Clark St & Chicago Ave,13303,Kingsbury St & Kinzie St,KA1503000043,41.896750,-87.630890,41.889177,-87.638506,casual,2021-06-11 13:40:19,2021-06-11 13:54:39,00:14:20
729580,6C9A65BFB41FD57C,classic_bike,2021-06-26 22:55:05,2021-06-26 23:04:38,Wells St & Polk St,SL-011,Kingsbury St & Kinzie St,KA1503000043,41.872596,-87.633502,41.889177,-87.638506,casual,2021-06-26 22:55:05,2021-06-26 23:04:38,00:09:33
729586,32D8203CE17F0348,electric_bike,2021-06-26 22:54:11,2021-06-26 23:04:47,Wells St & Polk St,SL-011,Kingsbury St & Kinzie St,KA1503000043,41.872602,-87.633845,41.889037,-87.638070,casual,2021-06-26 22:54:11,2021-06-26 23:04:47,00:10:36
729591,47BD346FAFB9BE6D,classic_bike,2021-06-30 17:35:10,2021-06-30 17:43:20,Clark St & Chicago Ave,13303,Kingsbury St & Kinzie St,KA1503000043,41.896750,-87.630890,41.889177,-87.638506,member,2021-06-30 17:35:10,2021-06-30 17:43:20,00:08:10
729592,52467C23D17C6AFE,classic_bike,2021-06-13 19:24:30,2021-06-13 19:34:11,Indiana Ave & 26th St,TA1307000005,State St & 19th St,SL-013,41.845687,-87.622481,41.856594,-87.627542,member,2021-06-13 19:24:30,2021-06-13 19:34:11,00:09:41